### ISSUE TITLE
NIH

### ISSUE THREAD

**Issue by alexeyshockov** [13rentgen/PropChecker#1]
Have you considered https://github.com/hapijs/joi as a solution? May it will be better not to invent something completely new... :)

**Comment by zt-sv** [comment]
First of all, because I can :)

Actually, I needed a lightweight, declarative and dependency-free library for fast check objects.
Maybe it's NIH, but Joi is a huge combine, while PropChecker is a simple validator.

**Comment by alexeyshockov** [comment]
OK, got it.

Anyway, good first issue for a JS library ;)
